project:
  title: Test Tutorial
  output-dir: ./_site/de

website:
  navbar:
    right:
      - href: ../de/Zusammenfassung.html
        text: Deutsch
      - href: ../en/Zusammenfassung.html
        text: English
      - href: ../sv/Zusammenfassung.html
        text: Svenska
      - href: ../da/Zusammenfassung.html
        text: Dansk
      - href: ../no/Zusammenfassung.html
        text: Norsk
  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "Kapitel 1"
        contents:
          - href: Testkapitel.html
            text: "Testkapitel"
          - href: Zusammenfassung.html
            text: "Zusammenfassung"


lang: de
